### PR TITLE
[WIP] [Papi may not working now] update with aapi and remove papi

### PR DESCRIPTION
**Pull request by abserari**
I don't know a little about papi why not working in my laptop. So I open a discuss here and update the code to adapt now.

- [ ] Change ppai to aapi. 
- [x] add proxy for env=True
- [ ] Don't know how to use picture URL because of referer check of it. like this URL https://i.pximg.net/c/600x1200_90_webp/img-master/img/2020/12/28/00/00/05/86588769_p0_master1200.jpg . not working with uploadFile with URL use telethon.

### CODE REVIEW

**Comment by Kyle2142** [comment]
Thanks for the contribution! However I can see this is still very much a work in progress (print statements, incorrect formatting etc).  
Please convert to draft and request my review when you think it is ready for merge

Additionally, I will mention that t.me/inlinepixivbot is still working (both inline mode, which asks telegram to download the images for us and `/top` in PM which downloads and uploads). Perhaps it does not work for you because of a geolocation restriction?

**Comment by abserari** [comment]
Yes, I test your bot many times. And read about the telethon and the pixivAPI.

In my case, It indeed has the geolocation restriction problem. So I add env support to use proxy with the request.

Could you please tell me what URL you give to telegram to download web file? Now I find that every URL I get is `https://i.pximg.net/c/360x360_10_webp/img-master/img/2020/12/29/13/04/10/86619782_p0_square1200.jpg`. I found that this URL should add a referrer header to visit. So does your picture URL doesn't like this?

**Comment by abserari** [comment]
and update for this, If I use a machine on google. It could get access and work at once. Thanks the docker. So I think the most problem for me is the geolocation restriction. 

I would try something to get the proxy as I do now. Now I only make the login use proxy, The public API seems not to use the proxy, maybe I should add env support on asyncio package.

This would be closed until I find something more.

**Comment by Kyle2142** [comment]
> Yes, I test your bot many times. And read about the telethon and the pixivAPI.
> 
> In my case, It indeed has the geolocation restriction problem. So I add env support to use proxy with the request.
> 
> Could you please tell me what URL you give to telegram to download web file? Now I find that every URL I get is `https://i.pximg.net/c/360x360_10_webp/img-master/img/2020/12/29/13/04/10/86619782_p0_square1200.jpg`. I found that this URL should add a referrer header to visit. So does your picture URL doesn't like this?

I think telegram adds the referrer header. To find the URL, enable debug logging and make an inline request.
  To use the bot in inline mode you shouldn't need a proxy, not sure what the problem is.
I'm open to adding proxy support to the bot though, so I'll be waiting for this PR to reopen

**Comment by abserari** [comment]
Now I use Go. https://github.com/abserari/golangbot. Sorry for the PR would not be reopened after. 
Tips: Only the Restriction location people canfind the proxy problem. And they need a cloud server to deploy their docker image or program which could pass them.

**Pull request closed without merging**
